In [1]:
import numpy as np

In [2]:
print(np.__version__)

2.1.2


In [3]:
arr = np.array([1,2,3,4,5])

In [4]:
type(arr)

numpy.ndarray

In [5]:
a = np.array(10)
b = np.array([1,2,3])
c = np.array([[1,2],[3,4]])

In [6]:
a.ndim

0

In [8]:
b.ndim

1

In [9]:
d = np.array([1,2,3,4],ndmin=5)

In [10]:
d

array([[[[[1, 2, 3, 4]]]]])

In [11]:
d[0][0][0][0][0]

np.int64(1)

In [12]:
b[0]

np.int64(1)

In [15]:
print(d[0][0][0][0][2])

3


In [20]:
c[1,0]

np.int64(3)

In [21]:
print(c)

[[1 2]
 [3 4]]


In [22]:
print(c[1,-1])

4


In [23]:
a = np.array([1,2,3,4,5,6,7,8,9])

In [24]:
print(a)

[1 2 3 4 5 6 7 8 9]


In [25]:
print(a[1:5])

[2 3 4 5]


In [26]:
print(a[1:])

[2 3 4 5 6 7 8 9]


In [27]:
print(a[:7])

[1 2 3 4 5 6 7]


In [28]:
print(a[-3:-1])

[7 8]


In [31]:
print(a[::5])

[1 6]


In [35]:
twoD = np.array([[1,2,3,4],[5,6,7,8]])

In [36]:
print(twoD[1,2:3])

[7]


In [42]:
print(twoD[1,2:3])

[7]


In [43]:
print(twoD[0:1,2])

[3]


In [44]:
print(twoD[0:2,1:3])

[[2 3]
 [6 7]]


In [45]:
print(twoD[0:4,2])

[3 7]


In [46]:
print(twoD[0:3,2])

[3 7]


In [47]:
print(twoD[0:0,2])

[]


In [53]:
print(twoD[0:2,2])

[3 7]


In [55]:
print(twoD[0:1,2])

[3]


In [56]:
print(twoD)

[[1 2 3 4]
 [5 6 7 8]]


In [57]:
print(twoD.dtype)

int64


In [58]:
fruits = np.array(["apple","banana","Kiwi","mango"])

In [59]:
print(fruits)

['apple' 'banana' 'Kiwi' 'mango']


In [60]:
print(fruits.dtype)

<U6


In [65]:
intArr = np.array([1,2,3,4,5,6],dtype="i4")

In [66]:
print(intArr.dtype)

int32


In [67]:
print(intArr.dtype)

int32


In [74]:
dum = np.array(["?",2,3,4],dtype="f")

ValueError: could not convert string to float: '?'

In [73]:
print(dum)

[1.1 2.  3.  4. ]


In [75]:
change = np.array([1.1,1.2,1.3])

In [76]:
print(change)

[1.1 1.2 1.3]


In [78]:
change.astype(int)

array([1, 1, 1])

In [79]:
print(change)

[1.1 1.2 1.3]


In [80]:
change.astype(bool)

array([ True,  True,  True])

In [81]:
change[1] = 0

In [82]:
print(change)

[1.1 0.  1.3]


In [83]:
change.astype(bool)

array([ True, False,  True])

In [84]:
copy = fruits.copy()

In [85]:
print(copy)
print(fruits)

['apple' 'banana' 'Kiwi' 'mango']
['apple' 'banana' 'Kiwi' 'mango']


In [86]:
copy

array(['apple', 'banana', 'Kiwi', 'mango'], dtype='<U6')

In [87]:
copy[1] = "Pineple"

In [88]:
print(copy)
print(fruits)

['apple' 'Pinepl' 'Kiwi' 'mango']
['apple' 'banana' 'Kiwi' 'mango']


In [89]:
view = copy.view()

In [90]:
print(copy)
print(fruits)
print(view)

['apple' 'Pinepl' 'Kiwi' 'mango']
['apple' 'banana' 'Kiwi' 'mango']
['apple' 'Pinepl' 'Kiwi' 'mango']


In [91]:
copy[0] = "Guava"

In [92]:
print(copy)
print(fruits)
print(view)

['Guava' 'Pinepl' 'Kiwi' 'mango']
['apple' 'banana' 'Kiwi' 'mango']
['Guava' 'Pinepl' 'Kiwi' 'mango']


In [93]:
print(copy.base)
print(fruits.base)
print(view.base)

None
None
['Guava' 'Pinepl' 'Kiwi' 'mango']


In [94]:
print(view.shape)

(4,)


In [95]:
print(c.shape)

(2, 2)


In [96]:
new = [1,2,3,4,5,6,7,8,9,10]

In [98]:
print(new)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [100]:
newArr = new.reshape(2,5)

AttributeError: 'list' object has no attribute 'reshape'

In [101]:
new = np.array([1,2,3,4,5,6,7,8,9,10])

In [102]:
newArr = new.reshape(2,5)

In [103]:
print(newArr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [105]:
new.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [107]:
new[10]=11

IndexError: index 10 is out of bounds for axis 0 with size 10

In [108]:
newA = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [109]:
print(newA.reshape(2,3,2))

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [110]:
print(newA.reshape(12,1,1))

[[[ 1]]

 [[ 2]]

 [[ 3]]

 [[ 4]]

 [[ 5]]

 [[ 6]]

 [[ 7]]

 [[ 8]]

 [[ 9]]

 [[10]]

 [[11]]

 [[12]]]


In [111]:
print(newA)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [113]:
print(newA.reshape(6,2))

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [114]:
print(newA.reshape(4,3))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [115]:
print(newA.reshape(2,3,2))

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [116]:
print(newA.reshape(6,2).base)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [120]:
print(newA.reshape(2,6,-1))

[[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]
  [10]
  [11]
  [12]]]


In [121]:
print(newA.reshape(-1).base)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [122]:
md = newA.reshape(2,3,2)

In [123]:
print(md)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [127]:
md = md.reshape(-1)

In [128]:
for x in md:
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [129]:
for x in fruits:
    print(x)

apple
banana
Kiwi
mango


In [130]:
fruits = fruits.reshape(2,2)

In [131]:
print(fruits)

[['apple' 'banana']
 ['Kiwi' 'mango']]


In [132]:
for x in fruits:
    print(x)

['apple' 'banana']
['Kiwi' 'mango']


In [133]:
for x in fruits:
    for y in x:
        print(y)

apple
banana
Kiwi
mango


In [134]:
print(newA)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [138]:
newA = newA.reshape(2,3,2)

In [139]:
print(newA)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [141]:
for x in newA:
    for y in x:
        #for z in y:
            print(y)

[1 2]
[3 4]
[5 6]
[7 8]
[ 9 10]
[11 12]


In [142]:
newA

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [144]:
for x in np.nditer(newA):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12
